### ISSUE TITLE
Mapbox GL JS not showing MVT layers

### ISSUE THREAD

**Issue by henhuy** [corteva/djangorestframework-mvt#14]
#### Code Sample, a copy-pastable example if possible

```
# models.py:

class State(models.Model):
    fid = models.IntegerField()
    ags = models.CharField(max_length=2)
    rs = models.CharField(max_length=2)
    sdv_rs = models.CharField(max_length=12)
    gen = models.CharField(max_length=22)
    bez = models.CharField(max_length=20)
    ibz = models.IntegerField()
    bem = models.CharField(max_length=2)
    sn_l = models.CharField(max_length=2)
    sn_r = models.CharField(max_length=1)
    sn_k = models.CharField(max_length=2)
    sn_v1 = models.CharField(max_length=2)
    sn_v2 = models.CharField(max_length=2)
    sn_g = models.CharField(max_length=3)
    fk_s3 = models.CharField(max_length=1)
    nuts = models.CharField(max_length=3)
    wsk = models.CharField(max_length=23)
    ewz = models.IntegerField()
    kfl = models.FloatField()
    shape_leng = models.FloatField()
    shape_area = models.FloatField()
    geom = models.MultiPolygonField(srid=4326)

    objects = models.Manager()
    vector_tiles = MVTManager()

# views.py:

class StatesMTVView(BaseMVTView):
    model = State

# urls.py:

urlpatterns = [
    ...
    path("states_mvt/", views.StatesMTVView.as_view()),
]

# map.html:

var map = new mapboxgl.Map({
      container: 'map',
      style: 'mapbox://styles/mapbox/streets-v11', // stylesheet location
      center: [10, 50], // starting position [lng, lat]
      zoom: 5 // starting zoom
    });

    var nav = new mapboxgl.NavigationControl();
    map.addControl(nav, 'top-right');

    map.on('load', function () {
      map.addSource('states_mvt', {
        'type': 'vector',
        "tiles": ["http://127.0.0.1:8001/states_mvt?tile={z}/{x}/{y}"],
        "tolerance": 10
      });

      map.addLayer({
        "id": "states_mvt",
        "source": "states_mvt",
        "source-layer": "states_mvt",
        "type": "line",
        "paint": {
          "line-color": "#FF0000",
          "line-width": 1
        }
      });
```

#### Problem description

I want to use `djangorestframework-mvt` with Mapbox GL JS. 
My `BaseMVTView` seems to work - I can download `.mvt` file when accessing `http://127.0.0.1:8001/states_mvt?tile={z}/{x}/{y}` via browser. Mapbox is downloading the layers (I can see it in browser traffics - but size is 0?), but does not show them - maybe it has to do with line `"source-layer": "states_mvt"`, as I don't know what to put there? 
Mapbox expects this entry (otherwise an error is thrown).
See https://docs.mapbox.com/help/glossary/source-layer/ and example https://docs.mapbox.com/mapbox-gl-js/example/vector-source/

Could not find anything about `source-layer` in the docs... 
Or can I somehow get [TileJSON](https://docs.mapbox.com/help/glossary/tilejson/) of `BaseMVTView` to get information about the vector tiles?

#### Expected Output

MVT Layer showing up in Mapbox GL JS.

#### Version Number

- djangorestframework-mvt 0.2.4
- Python 3.8
- Postgres 11.3
- PostGIS 2.5

**Comment by henhuy** [comment]
Found the solution!
source-layer is always named `"default"`.
See https://github.com/corteva/djangorestframework-mvt/blob/c6b4626c503a689ea051800d23529883f8f02918/rest_framework_mvt/managers.py#L82

A hint in the docs would be nice... I will do a PR if I find time.

**Comment by trollefson** [comment]
Thanks for the feedback.  I'll make sure the source-layer is properly documented in our next release.  This is not the first time this question has come up.
