### ISSUE TITLE
Using extra parameters causes wrong SQL query generation

### ISSUE THREAD

**Issue by bahron83** [corteva/djangorestframework-mvt#4]
An example request:
http://localhost:8000/api/v1/vector/tiles/?tile=8/134/91&layer=1
where **layer** column is a foreign key (I'm using a single table for storing multiple geometries)

I found 2 problems in **managers.MVTManager._create_where_clause_with_params** and **managers.MVTManager._build_query**

1. This line of code: 
`extra_wheres = " AND " + sql.split("WHERE")[1].strip()[1:-1] if params else ""`
removes the first and last character, causing a syntax error, as it strips out a double quote at the beginning of the string.

2. When filtering by foreign key, the query generated by Django includes an ORDER BY clause, but since the FROM clause is modified in **managers.MVTManager._build_query** method, the final query misses the JOIN statement, causing en error.

Since the ORDER BY is probably not needed, I think the fastest workaround to fix this issue would be changing the line declaring **extra_wheres** as follows:

`extra_wheres = " AND " + \
            sql.split("WHERE")[1].split('ORDER BY')[
                0].strip() if params else ""`

#### Version Number

- djangorestframework-mvt: 0.2.3
- Python: 3.6.9
- Postgres: 10
- PostGIS: 2.5

**Comment by trollefson** [comment]
Thanks for reporting the bug @bahron83.  I was able to reproduce some of your issue.

1. The extra_wheres line appears to be stripping out parenthesis from the WHERE clause.  The error occurs even when the filter column is not a foreign key.

2. I'm unable to reproduce a similar Django ORM query with an ORDER BY clause.  Will you please post an example?

I opened pull request https://github.com/corteva/djangorestframework-mvt/pull/5 to fix the issue in part 1.

Versions used for debugging:

- Django: 2.2
- djangorestframework: 3.10.3
- djangorestframework-gis: 0.14
- djangorestframework-mvt: .2.3
- Python: 3.6
- Postgres: 10
- PostGIS: 2.5
