### ISSUE TITLE
vector tile  integration in map box

### ISSUE THREAD

**Issue by metalica20** [corteva/djangorestframework-mvt#7]
#### Sample mapbox code to use vector tile in map below

`

> map.on('load', function() {
> map.addSource('mapbox-terrain', {
> type: 'vector',
> url: 'api/v1/core/districts.mvt/?tile={z}/{x}/{y}'
> });
> map.addLayer({
> 'id': 'terrain-data',
> 'type': 'line',
> 'source': 'mapbox-terrain',
> 'source-layer': 'contour',
> 'layout': {
> 'line-join': 'round',
> 'line-cap': 'round'
> },
> 'paint': {
> 'line-color': '#ff69b4',
> 'line-width': 1
> }
> });

> });

`

#### Problem description

As  shown above in the code block of mapbox  there are 2 required fields -

'id': '???',
'source-layer': '????',
  
These two parameters are required , so using djangorestframework-mvt’s to create vector tiles , what are the id and source-layer values to be used cause the vector tile does not load without 2 parameters being correct.

#### Expected Output

value to be used in those field ( id , source-layer )

#### Version Number

- djangorestframework-mvt ( latest)
- Python (3+)

**Comment by trollefson** [comment]
The `source-layer` should be set to `"default"`.  The layer name is set to default when the tile is created using ST_AsMVT in the MVTManager [here](https://github.com/corteva/djangorestframework-mvt/blob/master/rest_framework_mvt/managers.py#L82).  I don't think the value of `id` depends on the vector tile contents.
